/**
 * Message Rating Types
 * Based on API contract from frontend-guide-message-ratings.md
 */

/**
 * User rating enum matching backend contract
 * 0 = NotRated, 1 = ThumbsDown, 2 = ThumbsUp
 */
export enum UserRating {
  NotRated = 0,
  ThumbsDown = 1,
  ThumbsUp = 2,
}

/**
 * Request DTO for submitting message feedback
 * POST /api/feedback/MessageFeedback
 */
export interface MessageFeedbackRequest {
  /** GUID - The assistant message being rated (REQUIRED) */
  chatMessageId: string;
  /** GUID - User submitting the rating (OPTIONAL, backend uses authenticated user) */
  userId?: string;
  /** Rating value: 0=NotRated, 1=ThumbsDown, 2=ThumbsUp (REQUIRED) */
  userRating: UserRating;
  /** REQUIRED - User's explicit consent for conversation content to be accessed for analysis */
  consent: boolean;
  /** GUID - Chat containing the rated message (REQUIRED when editedAssistantMessage is provided) */
  chatId?: string;

  /** GUID - The user's question message ID (optional, enables content linkage) */
  parentMessageId?: string;
  /** Base64 encoded - Optional feedback text from user (always stored) */
  userMessage?: string;
  /** Base64 encoded - URL where rating was submitted */
  currentPageUrl?: string;
  /** Base64 encoded - Optional edited assistant response (requires chatId) */
  editedAssistantMessage?: string;

  /** Whether the rated message was generated by an AI agent. Default: false */
  generatedByAgent?: boolean;
  /** GUID of the agent (if generatedByAgent is true) */
  agentId?: string;
  /** Display name of the agent (if generatedByAgent is true) */
  agentName?: string;
}

/**
 * Helper to get display text for rating
 */
export const getUserRatingText = (rating: UserRating): string => {
  switch (rating) {
    case UserRating.NotRated:
      return "NotRated";
    case UserRating.ThumbsUp:
      return "ThumbsUp";
    case UserRating.ThumbsDown:
      return "ThumbsDown";
    default:
      return "Unknown";
  }
};
